import type { Metadata } from "next";
import { Keania_One, Anek_Bangla } from "next/font/google";
import "./globals.css";
import { NotificationProvider } from "./context/NotificationContext";
import { TimeSheetProvider } from "./context/TimeSheetContext";
import { Toaster } from "sonner";

const keanianOne = Keania_One({
  variable: "--font-keania-one",
  subsets: ["latin"],
  weight: "400"
});

const anekBangla = Anek_Bangla({
  variable: "--font-anek-bangla",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

console.log("test build");


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${keanianOne.variable} ${anekBangla.variable} antialiased`}
      >
        <NotificationProvider>
          <TimeSheetProvider>
            {children}
          </TimeSheetProvider>
        </NotificationProvider>
        <Toaster duration={5000} richColors={true} position="top-center" />
      </body>
    </html>
  );
}
