UPDATE `Absence`
SET `type` = 'OTHER'
WHERE `type` IN ('PERSONAL', 'PARENTAL', 'MARRIAGE', 'BEREAVEMENT');

ALTER TABLE `Absence`
MODIFY `type` ENUM('VACATION', 'OFFICIAL_HOLIDAYS', 'SICK', 'OTHER') NOT NULL;
